#!/bin/bash

# 给用户设置密码
echo "${USERNAME}:${USER_PASSWORD}" | chpasswd

# 取消Git的安全验证
gosu "${USERNAME}" git config --global http.sslVerify false

# 创建数据目录
if [ ! -d "${DATA_DIR}" ]; then
  gosu "${USERNAME}" mkdir "${DATA_DIR}"
fi

# 创建插件目录
if [ ! -d "${EXTENSION_DIR}" ]; then
  gosu "${USERNAME}" mkdir "${EXTENSION_DIR}"
fi

# 创建工作区目录
if [ ! -d "${WORKSPACE}" ]; then
  gosu "${USERNAME}" mkdir -p "${WORKSPACE}"
fi

# 初始化ZSH配置文件
ZSH_RC_FILE=${USER_HOME}/.zshrc
if [ ! -f "${ZSH_RC_FILE}" ]; then
  gosu "${USERNAME}" cp /etc/ohmyzsh/zshrc.sh "${ZSH_RC_FILE}"
fi

# 将主目录所有者改成系统创建的用户
permissionFile=${USER_HOME}/.permission.lock
if [ "${SET_PERMISSIONS}" = true ] && [ ! -f "${permissionFile}" ]; then
  chown -R "${USERNAME}":"${USERNAME}" "${USER_HOME}"

  if [ ! -f "${permissionFile}" ]; then
    gosu "${USERNAME}" touch "${permissionFile}"
  fi
fi
