#!/bin/bash

DOCKER_TARGET=""
MIRRORS=""
EXPERIMENTAL=""
DRIVER=""
# 接收Docker参数
DIND_FILE=/var/run/docker.sock
if [ ! -f "${DIND_FILE}" ]; then
  DOCKER_TARGET="--host=${DIND_FILE}"

  # 镜像
  IFS=', ' read -r -a mirrors <<< "${DOCKER_REGISTRY_MIRRORS}"
  for mirror in "${mirrors[@]}"
  do
    MIRRORS="${MIRRORS} --registry-mirror ${mirror}"
  done

  # 实验性功能支持
  if [ "${DOCKER_EXPERIMENTAL}" = true ]; then
    EXPERIMENTAL="--experimental"
  fi

  # 驱动
  DRIVER="--storage-driver ${DOCKER_STORAGE_DRIVER}"
else
  DOCKER_TARGET="--host=${DOCKER_HOST}"
fi

# 启动Docker守护进程
exec dockerd "${DOCKER_TARGET}" "${MIRRORS}" "${EXPERIMENTAL}" "${DRIVER}"
